import { baseConfig } from '@qsim/config/eslint/base'

export default [
  // Generated by `prisma generate`, rewritten wholesale on every schema
  // change. Linting it would only ever produce findings nobody can act on.
  { ignores: ['src/generated/**'] },
  ...baseConfig({ tsconfigRootDir: import.meta.dirname }),
]
