/**
 * The five things a circuit can be downloaded as, and how each one is built.
 *
 * The list is the single source of truth: the panel maps over it for its
 * buttons, the catalogs are keyed by the same ids, and
 * `ExportPanel.test.tsx` asserts that every id has a translation in all three
 * languages. Adding a format is adding an entry here plus three strings.
 *
 * ── WHERE EACH FORMAT COMES FROM ─────────────────────────────────────────
 *
 * The three text formats come from `@qsim/qasm`, which is a package precisely
 * because none of them needs a browser — the same bytes can be produced in the
 * API or in a worker, from the same document. The two picture formats are
 * built here, because they need the canvas components, which are React: see
 * `diagram.tsx`.
 *
 * ── THE FILE NAME ────────────────────────────────────────────────────────
 *
 * A downloaded file lands in a folder among a thousand others, so it is named
 * after the circuit rather than after the app. The title is user text in any
 * language, and a file name is not: `slugify` reduces it to something every
 * filesystem accepts, and an empty result falls back to a generic name rather
 * than producing a file called `.qasm`.
 */

import { toCircuitJson, toOpenQasm3, toQiskit } from '@qsim/qasm'
import type { Circuit } from '@qsim/schema'

import { MEDIA_TYPES } from './download'
import { circuitToSvg, type RenderToMarkup } from './diagram'
import { rasterise } from './raster'

/** Every export the editor offers, in the order the panel shows them. */
export const EXPORT_FORMATS = ['qasm3', 'qiskit', 'json', 'svg', 'png'] as const

export type ExportFormat = (typeof EXPORT_FORMATS)[number]

const EXTENSIONS: Readonly<Record<ExportFormat, string>> = {
  qasm3: 'qasm',
  qiskit: 'py',
  json: 'json',
  svg: 'svg',
  png: 'png',
}

/** Used when the circuit has no title, or none that survives slugification. */
export const FALLBACK_NAME = 'circuit'

/** Longest slug taken from a title, so no path runs into a filesystem limit. */
const MAX_SLUG_LENGTH = 48

/** What the exporters need beyond the circuit itself. */
export interface ExportContext {
  /** The document's title, for the file name and the header comment. */
  readonly title: string
  /** `<title>` of the SVG, translated by the caller. */
  readonly diagramTitle: string
  /** `<desc>` of the SVG, translated by the caller. */
  readonly diagramDescription: string
  /**
   * Loads `renderToStaticMarkup`.
   *
   * A thunk rather than the function itself, and awaited only by the two
   * formats that draw: the server renderer is some 150 kB that a reader
   * downloading OpenQASM has no use for, so it is fetched on the click that
   * needs it and never on the editor's own chunk.
   */
  readonly render: () => Promise<RenderToMarkup>
}

/** A finished export, ready for `saveFile`. */
export interface ExportedFile {
  readonly filename: string
  readonly blob: Blob
}

/** Builds one export. Asynchronous because rasterising a PNG is. */
export async function buildExport(
  format: ExportFormat,
  circuit: Circuit,
  context: ExportContext
): Promise<ExportedFile> {
  const filename = exportFilename(context.title, format)
  switch (format) {
    case 'qasm3':
      return text(filename, toOpenQasm3(circuit, options(context)), 'qasm')
    case 'qiskit':
      return text(filename, toQiskit(circuit, options(context)), 'python')
    case 'json':
      return text(filename, toCircuitJson(circuit), 'json')
    case 'svg':
      return text(filename, (await diagram(circuit, context)).svg, 'svg')
    case 'png':
      return {
        filename,
        blob: await rasterise(await diagram(circuit, context)),
      }
  }
}

async function diagram(circuit: Circuit, context: ExportContext) {
  return circuitToSvg(circuit, await context.render(), {
    title: context.diagramTitle,
    description: context.diagramDescription,
  })
}

function options(context: ExportContext) {
  // An untitled circuit passes no title at all rather than an empty one, so
  // the header comment reads "Generated by The Q Simulator." and not
  // "Generated by The Q Simulator — ".
  return context.title === '' ? {} : { title: context.title }
}

function text(
  filename: string,
  content: string,
  type: keyof typeof MEDIA_TYPES
): ExportedFile {
  return { filename, blob: new Blob([content], { type: MEDIA_TYPES[type] }) }
}

/** `Bell pair` + `qasm3` → `bell-pair.qasm`. */
export function exportFilename(title: string, format: ExportFormat): string {
  return `${slugify(title)}.${EXTENSIONS[format]}`
}

/**
 * A title reduced to a file name: lowercase ASCII words joined by hyphens.
 *
 * Accents are decomposed and their marks dropped, so `Téléportation` becomes
 * `teleportation` rather than losing its vowels — the app is trilingual and
 * two of the three languages put marks on ordinary words. Everything else that
 * is not a letter or a digit becomes a separator, which covers the path
 * characters (`/`, `\`, `:`) and the ones Windows refuses (`?`, `*`, `"`) in
 * one rule rather than in a list somebody has to keep complete.
 */
export function slugify(title: string): string {
  const slug = title
    .normalize('NFKD')
    .replace(/\p{M}/gu, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, MAX_SLUG_LENGTH)
    .replace(/-+$/, '')
  return slug === '' ? FALLBACK_NAME : slug
}
