import { CIRCUIT_SCHEMA_VERSION, type Circuit } from '@qsim/schema'
import { describe, expect, it } from 'vitest'

import {
  EXPORT_FORMATS,
  FALLBACK_NAME,
  buildExport,
  exportFilename,
  slugify,
} from './formats'

/**
 * The format table, the file names, and the three exports that need no
 * browser. The two that draw are in `diagram.test.tsx` and `raster.test.ts`.
 */

const BELL: Circuit = {
  schemaVersion: CIRCUIT_SCHEMA_VERSION,
  qubits: 2,
  clbits: 0,
  operations: [
    { id: 'op_1', gate: 'h', targets: [0], column: 0 },
    { id: 'op_2', gate: 'cx', targets: [1], controls: [0], column: 1 },
  ],
}

/** The renderer the text formats must never reach for. */
const NEVER_RENDERS = () => {
  throw new Error('a text export asked for the diagram renderer')
}

function context(title = 'Bell pair') {
  return {
    title,
    diagramTitle: 'Quantum circuit',
    diagramDescription: 'Two qubits.',
    render: NEVER_RENDERS,
  }
}

describe('slugify', () => {
  it.each([
    ['Bell pair', 'bell-pair'],
    ['  Bell   pair  ', 'bell-pair'],
    ['GHZ (3 qubits)', 'ghz-3-qubits'],
    ['Téléportation', 'teleportation'],
    ['Superposición', 'superposicion'],
    ['a/b\\c:d*e?f"g', 'a-b-c-d-e-f-g'],
  ])('turns %o into %o', (title, expected) => {
    expect(slugify(title)).toBe(expected)
  })

  it('falls back rather than producing a file with no name', () => {
    expect(slugify('')).toBe(FALLBACK_NAME)
    expect(slugify('///')).toBe(FALLBACK_NAME)
    // A title made entirely of characters no filesystem takes still has to
    // download as something.
    expect(slugify('日本語')).toBe(FALLBACK_NAME)
  })

  it('never ends in a separator, even when the cut lands on one', () => {
    const slug = slugify(`${'a'.repeat(47)} tail`)
    expect(slug.endsWith('-')).toBe(false)
    expect(slug.length).toBeLessThanOrEqual(48)
  })
})

describe('exportFilename', () => {
  it.each([
    ['qasm3', 'bell-pair.qasm'],
    ['qiskit', 'bell-pair.py'],
    ['json', 'bell-pair.json'],
    ['svg', 'bell-pair.svg'],
    ['png', 'bell-pair.png'],
  ] as const)('gives %s the extension its tools expect', (format, expected) => {
    expect(exportFilename('Bell pair', format)).toBe(expected)
  })

  it('gives every format in the table an extension', () => {
    for (const format of EXPORT_FORMATS) {
      expect(exportFilename('x', format)).toMatch(/^x\.[a-z]+$/)
    }
  })
})

describe('buildExport', () => {
  it('produces OpenQASM with the media type a toolchain recognises', async () => {
    const file = await buildExport('qasm3', BELL, context())
    expect(file.filename).toBe('bell-pair.qasm')
    expect(file.blob.type).toContain('openqasm')
    const text = await file.blob.text()
    expect(text).toContain('OPENQASM 3.0;')
    expect(text).toContain('cx q[0], q[1];')
    // The title reaches the file's header comment, not only its name.
    expect(text).toContain('Bell pair')
  })

  it('produces Python', async () => {
    const file = await buildExport('qiskit', BELL, context())
    expect(file.filename).toBe('bell-pair.py')
    expect(file.blob.type).toContain('python')
    expect(await file.blob.text()).toContain('circuit.cx(q[0], q[1])')
  })

  it('produces the native document, byte for byte the contract', async () => {
    const file = await buildExport('json', BELL, context())
    expect(file.filename).toBe('bell-pair.json')
    expect(JSON.parse(await file.blob.text())).toEqual(BELL)
  })

  it('names an untitled circuit generically and says nothing false', async () => {
    const file = await buildExport('qasm3', BELL, context(''))
    expect(file.filename).toBe(`${FALLBACK_NAME}.qasm`)
    const text = await file.blob.text()
    // Not "Generated by The Q Simulator — ", with the dash and nothing after.
    expect(text).toContain('Generated by The Q Simulator.')
    expect(text).not.toMatch(/—\s*$/m)
  })

  it('declares utf-8 on every text format', async () => {
    for (const format of ['qasm3', 'qiskit', 'json'] as const) {
      const file = await buildExport(format, BELL, context('Téléportation'))
      // A title with accents in it is why: a consumer guessing latin-1 turns
      // the header comment into mojibake.
      expect(file.blob.type).toContain('charset=utf-8')
    }
  })
})
